1 Obtaining the data:

We originally found the dataset on Kaggle at the following link: Dropout and Success: Student Data Analysis (kaggle.com)
The data was collected by the Polytechnic Institute of Portalegre in Portugal to build machine learning models that predict a student’s outcome (whether they drop out or complete their degree) based on various socioeconomic factors and academic performance. This dataset was created from several disjoint databases and includes students enrolled in different undergraduate degrees, such as agronomy, design, education, nursing, journalism, management, social service, and technologies.
The prediction problem was originally formulated as a a three-category classification task (dropout, enrolled, and graduate) at the end of the normal duration of the course. There is no universally accepted definition of dropout. The proportion of students who dropout varies between different studies depending on how dropout is defined, the data source, and the calculation methods. In this work the authors defined dropouts from a micro-perspective, where field and institution changes are considered dropouts independently of the timing these occur. This approach leads to much higher dropout rates than the macro-perspective, which considers only students who leave the higher education system without a degree.
Given that the number of libraries we can use is limited to the ones we saw during the course we decided to employ this dataset to answer a different research question.
The original study tries to assess one of three different outcomes by looking at data at enrollment and performance metrics during a three-year timeframe:
-	The student finishes within the three years of planned course activities
-	The student changes course or stops studying altogether
-	The student does not finish his studies in time, but is still enrolled and plans to finish the degree
Our analysis will focus on building a model to assign a probability score to new students , this score will quantify how likely a student will finish their course in a three year time-frame based on data collected about them at enrollment time 
In the following section we’ll delve into our dataset’s features in order and do some data processing

 
Data cleaning
Missing values: there were no missing values in the dataset.
Preparing the dataset: we decided to apply some changes in our dataset in order to make it better suited for our task, in this section we will go through the different variables of our dataset and talk about them in detail.

Demographic data:
- Marital status: Categorical variable indicating the marital status of the individual.
(1 – single 2 – married 3 – widower 4 – divorced 5 – facto union 6 – legally separated)
Looking at the dataset we found that we had 4 widowers and 6 legally separated, we collapsed them under the variable other, we also decided to merge the divorced and legally separated instances.
Nationality: Categorical variable indicating the nationality of the individual.
(1 - Portuguese; 2 - German; 6 - Spanish; 11 - Italian; 13 - Dutch; 14 - English; 17 - Lithuanian; 21 - Angolan; 22 - Cape Verdean; 24 - Guinean; 25 - Mozambican; 26 - Santomean; 32 - Turkish; 41 - Brazilian; 62 - Romanian; 100 - Moldova (Republic of); 101 - Mexican; 103 - Ukrainian; 105 - Russian; 108 - Cuban; 109 - Colombian).
- Displaced: Binary variable indicating whether the individual has been displaced (1 – yes 0 – no).
- Gender: Binary variable indicating the gender of the individual (1 for male, 0 for female).
- Age at enrollment: Numeric variable indicating the age of the individual at the time of enrollment.
- International: Binary variable indicating whether the individual is international (1 for yes, 0 for no).

SOCIOECONOMIC DATA

Mother/Father qualification:
Categorical variables indicating the mother and father occupation respectively, while the original dataset had 32 labels for all kinds of different jobs, we decided to merge some of the labels and make this a 3-label categorical variable. Jobs were split based on a White/Blue collar distinction, as shown in the table below.



- Mother’s/Father’s occupation: Numeric variable indicating the level of each parents’ qualification.
Again, we are working with many variables, so we decided to merge them based on the highest degree of education reached un until a university degree, thus ending up with three labels as shown below

# Group on (no secondary education, secondary education, bachelor's degree, 
# master's degree, phd or highter)

- Educational special needs: Binary variable indicating whether the individual has educational special needs (1 for yes, 0 for no).

- Debtor: Binary variable indicating whether the individual is a debtor (1 for yes, 0 for no).

- Tuition fees up to date: Binary variable indicating whether the tuition fees are up to date (1 for yes, 0 for no).

- Scholarship holder: Binary variable indicating whether the individual holds a scholarship (1 for yes, 0 for no).

MACROECONOMIC DATA:

- Unemployment rate: variable indicating the unemployment rate(Unemployment rate (%)).

- Inflation rate: Numeric variable indicating the inflation rate(Inflation rate (%)).

- GDP: Numeric variable indicating the Gross Domestic Product.

ACADEMIC DATA AT ENROLLMENT

- Application mode: Categorical variable indicating the mode of application.
(1 - 1st phase - general contingent 2 - Ordinance No. 612/93 5 - 1st phase - special contingent (Azores Island) 7 - Holders of other higher courses 10 - Ordinance No. 854-B/99 15 - International student (bachelor) 16 - 1st phase - special contingent (Madeira Island) 17 - 2nd phase - general contingent 18 - 3rd phase - general contingent 26 - Ordinance No. 533-A/99, item b2) (Different Plan) 27 - Ordinance No. 533-A/99, item b3 (Other Institution) 39 - Over 23 years old 42 - Transfer 43 - Change of course 44 - Technological specialization diploma holders 51 - Change of institution/course 53 - Short cycle diploma holders 57 - Change of institution/course (International)).
- Application order: Numeric variable indicating the order of application.
(between 0 - first choice; and 9 last choice).
- Course: Categorical variable indicating the chosen course.

(33 - Biofuel Production Technologies 171 - Animation and Multimedia Design 8014 - Social Service (evening attendance) 9003 - Agronomy 9070 - Communication Design 9085 - Veterinary Nursing 9119 - Informatics Engineering 9130 - Equinculture 9147 - Management 9238 - Social Service 9254 - Tourism 9500 - Nursing 9556 - Oral Hygiene 9670 - Advertising and Marketing Management 9773 - Journalism and Communication 9853 - Basic Education 9991 - Management (evening attendance)).
- evening attendance: Binary variable indicating whether the individual attends classes during the daytime or evening.
(1 for daytime, 0 for evening).

- Previous qualification: Numeric variable indicating the level of the previous qualification.

(Creiamo tabella con criterio simile a quello di mother and father occupation.



(1 - Secondary education 2 - Higher education - bachelor's degree 3 - Higher education - degree 4 - Higher education - master's 5 - Higher education - doctorate 6 - Frequency of higher education 9 - 12th year of schooling - not completed 10 - 11th year of schooling - not completed 12 - Other - 11th year of schooling 14 - 10th year of schooling 15 - 10th year of schooling - not completed 19 - Basic education 3rd cycle (9th/10th/11th year) or equiv. 38 - Basic education 2nd cycle (6th/7th/8th year) or equiv. 39 - Technological specialization course 40 - Higher education - degree (1st cycle) 42 - Professional higher technical course 43 - Higher education - master (2nd cycle)).

Academic data.
As explained above, we decided to exclude all the academic data from our model since this data will not help us answering the research question outlined above 

